### ISSUE TITLE
"Reject all" scraped entities  - does not work in any environment. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#182] opened 2019-06-20 21:47 UTC
rejects them one by one.

**Comment by ajmacdonald** [comment] 2019-06-21 17:52
Works on dev, doesn't work on prod
![image](https://user-images.githubusercontent.com/882444/59941658-bb656600-942b-11e9-98e8-c2fc43f1c37b.png)

**Comment by ajmacdonald** [comment] 2019-07-02 16:37
I'm having trouble reproducing this now even though I don't think anything's changed. @ilovan do you have a document that you can reproduce this with on https://cwrc-writer.cwrc.ca/ ?

**Comment by ajmacdonald** [comment] 2019-07-18 20:51
I believe this is a duplicate of https://github.com/cwrc/CWRC-WriterBase/issues/174

**Closed** 2020-01-19 08:59 UTC
Labels: bug
